name: {{name}} service
description: This is the description of the service to execute the {{name}} operation
style: OPERATION
urlPattern: {{urlPattern}}
methods:
    POST:
        summary: Execute the {{cName}} operation
        notes: Execute the {{cName}} operation
        # implementation: api.post{{cName}}
        urlPattern: {{urlPattern}}
        request:
            parameters: []
            cookies: []
            headers:
                -
                    field: Accept
                    content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                -
                    field: Accept-Encoding
                    content: "gzip, deflate"
            mockBody: postOperation-requestBody.json
        responses:
            -
                name: OK
                statusCode: &OkStatusCode
                reason: &OkReason
                # validationSchema: getCollection-responseBody-validationSchema.json
                cookies: []
                headers:
                    -
                        field: Content-Type
                        content: application/json
                mockBody: postOperation-responseBody.json
        testCases:
            -
                name: Execute the {{cName}} operation
                description: Execute the {{cName}} operation
                url: {{urlPattern}}
                template: testPostMethod.mustache
                request:
                    cookies: []
                    headers:
                        -
                            field : "Accept"
                            content: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"
                        -
                            field: "Accept-Encoding"
                            content: "gzip, deflate"
                    body: postOperation-requestBody.json
                response:
                    name: OK
                    statusCode: *OkStatusCode
                    reason: *OkReason
                    cookies: []
                    headers:
                        -
                            field: "Content-Type"
                            content: "application/json"
                    mockBody: postOperation-responseBody.json
                    # validationSchema: postCollection-responseBody-validationSchema.json
