projectName: {{projectName}}
apiVersion: v0.0.0
author: {{author}}
licence: {{licence}}
serviceUrlPrefix: {{serviceUrlPrefix}}
servicePort: {{servicePort}}
baseUrl: http://localhost:{{servicePort}}{{serviceUrlPrefix}}
servicesRoot: {{servicesRoot}}
services:
    - /monitoring/isAlive
    # To add new services, put here the path of the directory that contains the service.yml

{{#loginCredentials}}
loginCredentials:
    user: {{user}}
    pass: {{pass}}
{{/loginCredentials}}
